spring:
  profiles:
    active: company
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8081


---
spring:
  profiles: company
  datasource:
    url: jdbc:mysql://localhost:3306/my_data?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:

---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://192.168.141.142:3306/my_data?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: