spring:
  profiles:
    active: local
  application:
    name: driver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8082


---
spring:
  config:
    activate:
      on-profile: company
  datasource:
    url: jdbc:mysql://localhost:3306/my_data?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://192.168.247.142:3306/order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456


