spring:
  application:
    name: config
    instance_id: ${spring.application.name}:${random.value}
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:\wkk\project\interview\performance\doc\cloud\config
    client:
      hostname: localhost
  profiles:
    active: native
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: localhost
server:
  port: 8887

