server:
  port: 5001
spring:
  config:
    import: "optional:configserver:"
  application:
    name: config-client
    instance_id: ${spring.application.name}:${random.value}
  profiles:
    active: dev
  cloud:
    config:
      profile: dev
      enabled: true
      discovery:
        enabled: true
        service-id: CONFIG
    client:
      hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: "refresh,health,conditions,env,info"
    enabled-by-default: true
  endpoint:
    refresh:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: localhost
