spring:
  application:
    name: seeker
    instance_id: ${spring.application.name}:${random.value}
  cloud:
    client:
      hostname: localhost
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
server:
  port: 7001
